# Состояния для ConversationHandler
MAIN_MENU = 1
CALCULATOR_DEBT = 2
CALCULATOR_INCOME = 3
CONTACT_INFO = 4  # Добавьте эту строку!
CASE_DESCRIPTION = 5
AI_CHAT = 6
ADMIN_PANEL = 7
CALENDAR_MAIN = 8
CALENDAR_SELECT_TIME = 9
CALENDAR_SELECT_DAY = 10
SETTING_SCHEDULE = 11
ADMIN_DOCUMENTS = 12
ADMIN_CONTRACT = 13
ADMIN_RESEARCH = 14
ADMIN_RISK_ANALYSIS = 15
ADMIN_FINANCIAL = 16
